title: Ryan's First Page in Github
author: Ryan Andriant
email: ryanandriant@outlook.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  This page is for trial and learn purpose for learning github page feature.
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
